"""Added Similarity model

Revision ID: 164cfc37a367
Revises: 
Create Date: 2023-10-27 09:37:11.624391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164cfc37a367'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similarity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquery_id', sa.Integer(), nullable=False),
    sa.Column('other_inquery_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['inquery_id'], ['inquery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similarity')
    # ### end Alembic commands ###
